### ISSUE TITLE
Getting started doc is broken to run init cmd

### ISSUE THREAD

**Issue by fzxu** [99designs/gqlgen#609]
### Expected Behaviour

should continue generate what ever it should.

### Actual Behavior

`merging failed: unable to build object definition: unable to find type github.com/99designs/gqlgen/graphql/introspection.InputValue`

### Minimal graphql.schema and models to reproduce

```
type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
}

type Query {
  todos: [Todo!]!
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

**Comment by mathewbyrne** [comment]
Are you using the latest version 0.8.1, and are you using Go Modules or dep to initialise?

**Comment by fzxu** [comment]
I am following the `dep` way: https://gqlgen.com/getting-started-dep/

I did not specify which gqlgen version. I believe it is from master.

**Comment by mathewbyrne** [comment]
Ok, yeah dep isn't getting the ambient imports it needs from `https://github.com/99designs/gqlgen/blob/master/ambient.go`.

As a workaround for now, if you include these imports in your `scripts/gqlgen.go` file from the getting started docs, you should be able to get the `init` command running.

**Comment by mathewbyrne** [comment]
Fixed in #628

**Comment by flaviamissi** [comment]
Same problem here with `dep`, `gqlgen` `v0.8.2.
Tried adding the imports listed in `ambient.go` to my `scripts/gqlgen.go` but that didn't fix it for me either. :/

**Comment by fzxu** [comment]
following the doc https://gqlgen.com/getting-started-dep, I got another error:

`panic: unable to find type github.intuit.com/fzxu/gqlgen_todos/gettingstarted.Todo`

Even I have package `gettingstarted` created under project root and the `todo.go` file created.

What I don't understand is the file with extension `.Todo`. what is that file? should I create that file? What content it should be?

**Comment by fzxu** [comment]
@mathewbyrne could you follow up?

**Comment by fzxu** [comment]
I got the new error `merging failed: unable to build object definition: unable to find type github.xxx.com/fxu/gqlgen_todos.Todo`

I have the `todo.go` file under `gqlgen_todos` package. What could be wrong? @mathewbyrne

**Comment by mathewbyrne** [comment]
I'm unable to reproduce in `0.8.2`:

```
$ mkdir tmp
$ cd tmp
$ ls
$ mkdir scripts
$ vim scripts/gqlgen.go
$ dep init
  Locking in v0.5.1 (7087cb7) for transitive dep github.com/hashicorp/golang-lru
  Locking in v1.20.0 (cfb3883) for transitive dep github.com/urfave/cli
  Locking in v1.1.2 (05741cd) for transitive dep github.com/vektah/gqlparser
  Locking in master (bb1270c) for transitive dep golang.org/x/tools
  Locking in v0.8.1 (ba968bf) for transitive dep github.com/pkg/errors
  Using ^0.8.2 as constraint for direct dep github.com/99designs/gqlgen
  Locking in v0.8.2 (ee06517) for direct dep github.com/99designs/gqlgen
  Locking in v1.4.0 (66b9c49) for transitive dep github.com/gorilla/websocket
  Locking in v2.2.2 (51d6538) for transitive dep gopkg.in/yaml.v2
  Locking in v1.0.1 (834b435) for transitive dep github.com/agnivade/levenshtein
$ vim schema.graphql
$ go run scripts/gqlgen.go init
Exec "go run ./server/server.go" to start GraphQL server
$ dep ensure
$ go run ./server/server.go
2019/03/20 08:22:09 connect to http://localhost:8080/ for GraphQL playground
```
If you're still having issues can you give the exact steps to reproduce.

Also worth noting that this `dep` method wont supported much further once Go Modules gets wider adoption.  If it's possible for you I would definitely recommend using Go 1.12+ and Go Modules.

**Comment by fzxu** [comment]
that part works for me. but if you go a little further in that doc: https://gqlgen.com/getting-started-dep/#create-the-database-models

what I don't know is the `.Todo` file. It was not asked to create or go file.

**Comment by mathewbyrne** [comment]
Ok I can see a couple of problems in the dep docs:

1. You need to ensure that the `todo.go` file has the correct package name for it's location.  So for example, if my project was in `github.com/99designs/todos` then the package name should also be `todos`

2. Check that your mapping in `gqlgen.yml` is also correctly pointing to the right model.  So for the example above:

```
models:
  Todos:
    model: github.com/99designs/todos.Todo
```

**Comment by fzxu** [comment]
I think I followed that correctly. The package name is `gqlgen_todos` and the model path is `github.xxx.com/fxu/gqlgen_todos.Todo`

If I change to a wrong path it will say `can not find file`. but it show `can not find type` which seems both the path and package are correct.

**Comment by mec07** [comment]
Clearing out all the generated files, then executing:

```
go mod init
```

and then rerunning gqlgen resolved these types of issues for me.

**Comment by Szymongib** [comment]
If anyone using `dep` still having that issue I suggest trying to add 
```  
[[prune.project]]
        name = "github.com/99designs/gqlgen"
        non-go = false
```
to the `Gopkg.toml` file, as apparently, the library is using some Go templates files for code generation.
I use version `0.9.0`.

**Comment by KISINGA** [comment]
For anyone still struggling with this, 
take a look at [this answer](https://stackoverflow.com/a/56930549/5927361)
Make sure to run `go mod tidy` after conversion

**Comment by mmacheerpuppy** [comment]
Starting to see this issue again

**Comment by timohuovinen** [comment]
Looks like the issue is caused by go not downloading the introspection directory, at least I don't see it in my `vendor`, copying it over manually from this repo fixed the issue for me.

**Comment by mwillfox** [comment]
For anyone running into this issue on v0.17.8, @timohuovinen has the correct fix. You can force mod to grab the introspection directory by updating your tools.go:
`
//go:build tools
// +build tools

package tools

import (
	_ "github.com/99designs/gqlgen"
	_ "github.com/99designs/gqlgen/graphql/introspection"
)
`

**Comment by PrashantRaj18198** [comment]
This does not work when you are using a 'vendor' folder. Check your vendor folder the 'introspection.Directive' file is missing there. As a work around, remove the vendor folder, delete all the generated files and rerun the `.../gqlgen init` command.

**Comment by mufaddaltahir** [comment]
> For anyone running into this issue on v0.17.8, @timohuovinen has the correct fix. You can force mod to grab the introspection directory by updating your tools.go:
> 
> ```
> //go:build tools
> // +build tools
> 
> package tools
> 
> import (
> 	_ "github.com/99designs/gqlgen"
> 	_ "github.com/99designs/gqlgen/graphql/introspection"
> )
> ```

did not fix the issue for me 
gqlgen version v0.17.16
golang version 1.21.6
