### ISSUE TITLE
autobind on multiple packages has strange priority

### ISSUE THREAD

**Issue by moxar** [99designs/gqlgen#845]
### What happened?

When setting multiple `autobind` values, witch package containing a type with a similar name, there is no way to force priority.

### What did you expect?

For each type, I expect gqlgen to do the binding with the first package in "autobind", and fallback to the second (and so on...) if the model is not found.

In my example:
- I want gqlgen to use map `ProjectFilter` to `graphqlapi.ProjectFilter`
- I want gqlgen to use map `Project` to `httpapi.Project`
- I want gqlgen **not to use** `httpapi.ProjectFilter`

### Minimal graphql.schema and models to reproduce

```go
package httpapi

type Project struct{
  ID int `json:"id"`
  Name string `json:"name"`
}

type ProjectFilter struct{
  ID int `json:"id"`
}
```

```go
package graphqlapi

type ProjectFilter struct{
  Name string `json:"name"`
}
```

```graphql
type Project{
  id: Int!
  name: String!
}

type ProjectFilter{
  name: String!
}
```

```yml
# .gqlgen.yml
...
autobind:
  - graphqlapi
  - httpapi

```

### versions
- gqlgen v0.9.3
- go version go1.12.5 linux/amd64
- go modules

**Comment by vektah** [comment]
fixed by https://github.com/99designs/gqlgen/pull/872

**Comment by moxar** [comment]
Despite upgrading to `v0.10.1`, the issue is still there: I cannot force priority.
The consequence is that, if I don't map each model one...

* gqlgen always maps the schema types to the httpapi types
* the graphqlapi types that are declared are never used

**Comment by vektah** [comment]
Sorry if that pr wasn't clear, you can now use the short package name as long as it's on the autobinl path eg "model.User"

**Comment by moxar** [comment]
I noticed indeed, but this does not solve the issue here. 

What I aim to do is to use the autobind feature to avoid mapping each schema's type to a package's type. Here, I need...

* `ProjectFilter` type (declared in the schema) mapped to `graphqlapi.ProjectFilter`
* `Project` type (declared in schema too) mapped to `httpapi.Project`

To do so, I declared in the `gqlgen.yml` file:
```yml
autobind:
  - graphqlapi
  - httpapi
```

But when I do so, the graphqlapi types are never used: gqlgen uses httpapi package for both `Project` and `ProjectFilter`.

My current workaround consists in _hand mapping_ each type, but I would want gqlgen to "first look into graphqlapi, if the model is missing, look into httpapi". But doing so, I end up with a lot of lines in the model mapping, which could be easily discarded.

Do you think that this could be solved ?

**Comment by vektah** [comment]
Ok that sounds like a bug, it's meant to be a priority search path with the short package syntax to override when there is a type name collision
